### PR TITLE
Take care of unwanted (negative) indices

### PR DESCRIPTION
**Pull request by nueckman**
Due to protected visibility of BookListIterator::$currentBook we can't assure that $currentBook will always be a valid index. So let's take another road.

Same goes for BookList::getBook($bookNumberToGet). The argument could also be a negative integer.

### CODE REVIEW

**Comment by domnikl** [comment]
For the `BookListIterator` things will be better if `$bookList` wasn't protected but private instead. Also the reverse iterator should not extend it. It is a whole new example that focuses on a different implementation detail but does not add anything to explain the iterator pattern itself.

**Comment by nueckman** [comment]
I'm not even sure if this is a pattern ;) @domnikl

**Comment by nueckman** [comment]
Here you go

**Comment by domnikl** [comment]
it's not one of the GoF patterns, but that doesn't mean it is not a pattern. Wikipedia calls it a pattern, too ;-) https://en.wikipedia.org/wiki/Iterator_pattern

Looks good now, I'll merge it. Thx!

**Pull request merged**
