### PR TITLE
Turkish translations.

### PR DESCRIPTION
**Pull request by ahmetelcik**

### CODE REVIEW

**Comment by k-gun** [comment]
Hi there, @piotrgradzinski! Finally we are done with Turkish translations. Could you check out our work ASAP, please? People can not wait for it. :) 
Also, I would like to ask that when Read the Docs takes these translations in?
Cheers!

**Comment by piotrgradzinski** [comment]
Hi @ahmetelcik ! 
Thank you for your first and that big contribution!

I love your enthusiasm! 

Before my own contribution to the polish translation I was not aware that adding completely new translation is not just one click. There need to be another project on readthedocs in place, with different repository attached (yes, this repo needs to be copied) and then linked as a translation to the main readthedocs version. Yeah...

I think that we should ask @domnikl for help on that, at least at creating repo and readthedocs project. I can do the rest. @domnikl share with us other ideas if you have some. 

On the other hand I think we should think through the approach on translations because current solution does not look like most effective one.

**Comment by k-gun** [comment]
Hi @piotrgradzinski! Actually we did it together all (you can see the translator names in files) and yes, we are excited to see Turkish translation on Read the Docs. :)

By the way, I noticed that I missed something, apologies; So, in behalf of colleagues in my the translator team, I would like to say "THANK YOU!" to @domnikl 'cos he made such work that will be a good source and reference for all who like to create projects that designed well. All we are happy and thankful to him, thank you!

**Comment by domnikl** [comment]
Thank you all for the hard work and translating it in turkish!

Yes the process of bringing this to RTD is not that simple. After merging this in I have to fork the repo and create a new project on readthedocs.org and then link it as a translation to the original project. Sadly, I think there is no other option to simplify that process. 

Most of the translations haven't been updated in a long time, most of them since they were initially translated. I will try to update them in the next few days, but I fear that msg IDs have been changed and that will break a lot of translations.

But first I will create the project for the turkish translation, thanks again to everyone who worked on this, your effort is much appreciated!

**Comment by k-gun** [comment]
Hi @domnikl! Hereby, I would like to ask you that, could you permit us to;

- We think about to make book these **Turkish** translations with example codes in order to give to participants freely in some events, meetups, etc. or donate to some educational institutions.
- We think about to present these **Turkish** translations with example codes on some web sites as an information source.

adhering to MIT License.

Also your effort is much appreciated, thank you!

**Comment by domnikl** [comment]
Hey @k-gun,

you are free to do all that, but please add a link or hint to this repository so that people can find it and contribute to it. Actually, you can already get it as a PDF from ReadTheDocs: https://media.readthedocs.org/pdf/designpatternsphp-tr/latest/designpatternsphp-tr.pdf

And if you do make a book out of it, could you send me a copy? I don't speak turkish (yet) and it would be my first book in turkish ;)

And thanks for asking that question, I know asking this is not common and although the license allows it, many others would just take without asking permission first 👍

**Comment by k-gun** [comment]
Ahhh @domnikl! Komm mal, bitte! :) Es ist nicht **türkisch**, aber **Türkisch**! Ihre Sprache ist in dieser Bezug so sensibel, so, warum achten Sie beim Schreiben spezieller Namen nicht auf die Grammatik? :)

Actually, as a hobby, I like redaction (grammar) and I will try to redact it first just because it needed. Also, I will reference all the stuff where needed.

Of course I have to ask first before doing anything with your labor, your work. And I do not carry about others, or about what others do. Because I am responsible myself, what myself do.

So also, surely I will, I will send a copy of your work to you with pleasure.

Danke nochmal, und Bis Später!

**Pull request merged**
