### PR TITLE
`es_ES` translation part 1

### PR DESCRIPTION
**Pull request by desarrolla2**
Hi!

I will start with spanish translation.

I have no experience in translations, so i'm sorry for errors or anywhere, i suppose that i will learn along the way.

Please tell me what ever i will do wrong.

This is only a test that all will be ok.

Regards

### CODE REVIEW

**Comment by shangguokan** [comment]
This test is right, you can check [Translation Rule/Hint](https://github.com/domnikl/DesignPatternsPHP/issues/134)
or just follow what the [russian translation do](https://github.com/domnikl/DesignPatternsPHP/tree/master/locale/ru/LC_MESSAGES).

thanks for your contribution!

**Comment by desarrolla2** [comment]
Hi @shangguokan i have one question

What about po files headers

For example
``` po
"Project-Id-Version: DesignPatternsPHP 1.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-05-29 12:18+0200\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"PO-Revision-Date: \n"
"Last-Translator: Daniel González <daniel@desarrolla2.com>\n"
"Language-Team: \n"
"X-Generator: Poedit 1.5.4\n"
```
What header will should stay and which should be clear

**Comment by desarrolla2** [comment]
can you create the project on readthedoc so i can see how the result is?

**Comment by shangguokan** [comment]
http://designpatternsphp-es.readthedocs.org/es/latest/README.html

**Pull request merged**
