### PR TITLE
Fix grammar typos.

### PR DESCRIPTION
**Pull request by k-gun**

### CODE REVIEW

**Comment by piotrgradzinski** [comment]
Hi @k-gun! 
Good catch. Actually it won't be that simple to merge since all the locales are using msg strings for translation so your change will brake translation. Can you also please update proper msg_ids in corresponding translations?

**Comment by k-gun** [comment]
Hi @piotrgradzinski, I did not touch the other translation files actually, but just a template file. How does it break the others? Also could not get this "Can you also please update proper msg_ids in corresponding translations?", sorry. :( What are you asking for, where I can update, whicch msgid's? Confused. :)

**Comment by piotrgradzinski** [comment]
@k-gun take a look at this localised file https://github.com/domnikl/DesignPatternsPHP/tree/master/locale/pl/LC_MESSAGES/Behavioral/Memento

Inside you have 
```
#: ../../Behavioral/Memento/README.rst:7
msgid ""
"It provides the ability to restore an object to it's previous state (undo "
"via rollback) or to gain access to state of the object, without revealing "
"it's implementation (i.e., the object is not required to have a function "
"to return the current state)."
msgstr ""
"Implementacja tego wzorca umożliwia przywrócenie obiektu do poprzedniego stanu (poprzez wycofanie zmian) "
"lub uzyskaniu dostępu do stanu obiektu bez wiedzy na temat wewnętrznej implementacji obiektu "
"(w sytuacji, gdy na przykład obiekt nie posiada metody pozwalającej na zwrócenie jego stanu)."
```

You've made changes to this part in `Behavioral/Memento/README.rst` in main repo directory the translation will be broken and on each translated version you will have one paragraph in english and rest in polish for example. This is because the portion of text from localised file enclosed in `msgid` won't be found in main file. 

I know this is the pain and redundancy but you have to fix those typos `locale` folder as well.

At this point I am not aware of any other solution that will help with that. If you have some ideas please share!

**Comment by k-gun** [comment]
Ok, got it! :) 
So, I undid all changes now (in `locale/template/LC_MESSAGES/Behavioral/Memento/README.pot`). 
Thanks for attention @piotrgradzinski.

**Pull request closed without merging**
