### PR TITLE
DRY things up a bit

### PR DESCRIPTION
**Pull request by FatBoyXPC**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
It's redundant to call methods inside a class. Could you explain why do you do these changes?

**Comment by axelitus** [comment]
It's redundant from an optimization point of view, but from a consistency point of view it makes sense that there's only one way to assign values to properties. This makes the code management and debugging easier later on.

**Comment by FatBoyXPC** [comment]
It's not redundant at all. What's redundant is writing the same line of code twice, especially when there's a method available to avoid writing that same line of code ever again.

**Comment by dev-NorseBlue** [comment]
I agree with that and I just noticed I forgot a very important word in my last comment: "It _may seem_ redundant from an optimization point of view". Though it's an extra function call, I prefer doing things as @FatBoyXPC suggests for the same reasons he just explained.

**Comment by axelitus** [comment]
I agree with that and I just noticed I forgot a very important word in my last comment: "It may seem redundant from an optimization point of view". Though it's an extra function call, I prefer doing things as @FatBoyXPC suggests for the same reasons he just explained.

**Comment by FatBoyXPC** [comment]
@axelitus while we're in agreement here, I found another spot that does something similar. The [Value](https://github.com/domnikl/DesignPatternsPHP/blob/master/More/EAV/Value.php) object in the EAV pattern has some similarity here, however, there is one difference: the setter assumes the value has already been set by the constructor. However, once `$this->attribute = $attribute` happens, that makes the `$this->attribute->removeValue($this)` essentially useless. There are 2 lines of code written rather than one, which makes this arguably a more important change than the first one I submitted.

Your thoughts?

**Comment by axelitus** [comment]
Not really, as I understand the ```$this->attribute->removeValue($this)``` is detaching the value from the attribute. There could be another reference to the attribute object elsewhere in your code, thus replacing the object's attribute with ```$this->attribute = $attribute``` would not make the previous owned attribute disappear and it would be a mistake if it still referenced the value that should be detached. I don't see any useless lines of code in this.

You could however modify the code to this:
```
    public function __construct(Attribute $attribute)
    {
        $this->setAttribute($attribute);
    }

    public function setAttribute(Attribute $attribute)
    {
        $this->attribute && $this->attribute->removeValue($this); // Remove value from current attribute
        $attribute->addValue($this); // Add value to new attribute
        $this->attribute = $attribute;
        return $this;
    }
```

This way you do not repeat code, and ensure that the call to removeValue should only be made if an attribute has already been set.

**Comment by FatBoyXPC** [comment]
I like your proposed solution. Quick question, though. If other bits of code referenced this same attribute, why would we want that value to be removed just because we changed this value's attribute? This seems like a not so safe side effect.

**Comment by axelitus** [comment]
Because an attribute can contain multiple values, and a value may be shared with other attributes. It would make sense in some cases were in others would, as you say, not so _safe_. Would need to dig some more on the code, as I did not review the EAV in full.

**Comment by FatBoyXPC** [comment]
I didn't either. I'll add the change you mentioned and mention in the PR that the line could potentially be removed in full as well!

**Pull request merged**
