### PR TITLE
DesignPatternsPHP available on Read the Docs

### PR DESCRIPTION
**Pull request by shangguokan**
### address: http://designpatternsphp.readthedocs.org
| - Q. - | - A. - |
| ------ | ------ |
| Tickets | #114 , #115 |
| Type |  Feature / Documentation |
| Techniques | Sphinx + reStructuredText +  readthedocs.org|
| Participants  | @domnikl , @eddiejaoude , @aik099|

### what has changed and will change:
- [x] use [Pandoc](http://johnmacfarlane.net/pandoc/) to convert all the **README.md** to **README.rst**  *in script read-the-docs.sh*
- [x] use sphinx tag: [literalinclude](http://sphinx-doc.org/markup/code.html#directive-literalinclude) to embed all related php files in the **README.rst** of every pattern. *in script read-the-docs.sh*
- [x] sphinx-quickstart
- [x] create TOC tree (index of projet)
- [x] host on Read the docs
- [x] add Wikipedia link
- [x] bug fix
- [x] reorder php embed files (Top-down)
- [x] revision
- [x] finish and ready to merge

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Nice work, looks good! :+1:

**Comment by domnikl** [comment]
It looks really, really great! :+1: What do you mean by "reorder php files embed (Top-down)"?

**Comment by shangguokan** [comment]
For example, for **AbstractFactory**, this pattern.
php files embed should be in this order (Top-down):

1. AbstractFactory.php
2. HtmlFactory.php
3. JsonFactory.php
4. MediaInterface.php
5. ...

but now, [Text.php](http://designpatterns-php.readthedocs.org/en/latest/Creational/AbstractFactory/#code) is the first one.

**Comment by shangguokan** [comment]
@eddiejaoude Hi Eddie, if it is possible, can you delete [this project](https://readthedocs.org/projects/designpatternsphp/), because i can't create a same projet named "designpatternsphp", that is why i use "designpatterns-php". but i think "designpatternsphp" is much better. Thank you!

**Comment by eddiejaoude** [comment]
@shangguokan Sure. I will do it now.

**Comment by eddiejaoude** [comment]
@shangguokan Done :smile:

**Comment by shangguokan** [comment]
@eddiejaoude Great! :+1: Thanks, i will transfer it designpatternsphp

**Comment by domnikl** [comment]
@shangguokan I understand that they need to be ordered by hand or is there any way we can keep .rst files generated from your shell script and sort them autmatically?

**Comment by shangguokan** [comment]
@domnikl I think sort the order in .rst by hand is the only way

**Comment by shangguokan** [comment]
@domnikl This pull is ready to merge :smile: 
Can you add me as one of ***Collaborators***? because readthedocs.org use my account GitHub to import repo. i need the access permission to change shangguokan/DesignPatternsPHP to domnikl/DesignPatternsPHP.
And after that i can maintain the part of readthedocs.org

**Comment by domnikl** [comment]
I merged it in, thank you @shangguokan and also @eddiejaoude for your great work! And I added @shangguokan as a collaborator, it would be great if you can maintain that part of DesignPatternsPHP.

**Comment by eddiejaoude** [comment]
Great team effort :+1: #GottaLoveOpenSource

**Comment by shangguokan** [comment]
Thanks, now it is on domnikl/DesignPatternsPHP :smile:

**Pull request merged**
