### PR TITLE
Replace array storage with SplObjectStorage

### PR DESCRIPTION
**Pull request by bocharsky-bw**
If you already use SPL interfaces in your example, maybe better to use `SplObjectStorage` too instead of `array` to store observers with `attach` and `detach` convenient methods?
@domnikl What do you think?

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
If it looks good I'll fix broken tests

**Comment by nueckman** [comment]
> If it looks good I'll fix broken tests

Nice behavior .. 

IMO ```SplObjectStorage``` could confuse inexperienced developers by distracting them from the topic (e.g. the pattern).

**Comment by bocharsky-bw** [comment]
@nueckman Nevertheless we used `SplObserver` and `SplSubject` instead of realize them manually for simplicity. I don't think `SplObjectStorage` will be distracting a lot.

**Comment by nueckman** [comment]
Like i said. It's just an opinion.

**Comment by domnikl** [comment]
@bocharsky-bw I like your change, makes this a lot more readable and I also think that while we already used other SPL classes this will be distracting more than the currently used classes. Could you please fix the test  "DesignPatterns\Behavioral\Observer\Tests\ObserverTest::testAttachDetach" so I can merge it in?

**Comment by bocharsky-bw** [comment]
@domnikl Yes, of course. I'll fix it a bit later

**Comment by bocharsky-bw** [comment]
@domnikl I fixed tests. What do you think?

**Comment by domnikl** [comment]
Looks good, I am merging it in. Thanks for your contribution!

**Pull request merged**
