### PR TITLE
Vagrant ansible environment setup

### PR DESCRIPTION
**Pull request by eddiejaoude**
No need to install the correct version of **PHP** etc, this small and simple vagrant & ansible script will build a new VM environment.

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
It looks interesting!

**Comment by eddiejaoude** [comment]
Thanks. I wanted to make it easy for people to setup the project with a few commands without polluting their host machine. This way, it installs everything required in a sandbox (VM) with the correct versions of PHP etc. The code is kept outside the VM on the host machine and mounted (shared) in.

**Comment by eddiejaoude** [comment]
**PHP** version

```bash
vagrant@design-patterns:/vagrant$ php -v
PHP 5.6.11-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by domnikl** [comment]
Great idea, but it looks like phansible adds a lot of clutter that we don't need. E.g. why do we need pecl or pear or php-fpm?

**Comment by eddiejaoude** [comment]
I will remove those, then rebuild to test it all again.

**Comment by domnikl** [comment]
:+1:

**Comment by KIVagant** [comment]
Thank's.

**Comment by eddiejaoude** [comment]
All suggested changes should be applied now

**Comment by eddiejaoude** [comment]
@domnikl any more changes required on this?

**Comment by domnikl** [comment]
@eddiejaoude it just needed to test it on my machine. Works like a charm. Thanks for the great idea and work!

**Comment by eddiejaoude** [comment]
> it just needed to test it on my machine

Sure of course.

> Works like a charm. 

Great! :smile: 

> Thanks for the great idea and work!

No problem :+1:

**Pull request merged**
