### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by domnikl**
This is the german translation for DesignPatternsPHP located at http://designpatternsphp-german.readthedocs.org/de

### CODE REVIEW

**Comment by domnikl** [comment]
@shangguokan can you please add `designpatternsphp-german` as translation for "de" to the original RTD project at `http://designpatternsphp.readthedocs.org`?

**Comment by domnikl** [comment]
ping @shangguokan

**Comment by shangguokan** [comment]
@domnikl sorry for the late response
It's added, http://designpatternsphp-de.readthedocs.io/de/latest/
After you merge this PL, the translation will replace the original english messages

**Comment by domnikl** [comment]
@shangguokan no problem and thanks!

**Pull request merged**
