### PR TITLE
remove composer.phar

### PR DESCRIPTION
**Pull request by TomasVotruba**
Standard nowadays

### CODE REVIEW

**Comment by domnikl** [comment]
What is standard for you might not be standard for every PHP developer. I keep them in repositories usually to avoid installing all the dependencies from different sources and keep it batteries included. I am fine with that though if you add a section about how to install it in the README file and a `.gitignore` entry for it.

**Comment by malukenho** [comment]
@TomasVotruba :+1:

**Comment by bocharsky-bw** [comment]
I think `composer.phar` file don't help for developers who don't know what is it. But if developer know what is it, I'm pretty sure that he can download/install it himself.
I also think the better way is to remove this file from repo and add direct link to the Composer installation instruction to README file.
@TomasVotruba :+1:

**Comment by TomasVotruba** [comment]
@bocharsky-bw Well said.

**Comment by fadoe** [comment]
@TomasVotruba :+1: 
@bocharsky-bw :+1:

**Comment by timgws** [comment]
Guys, please do not vote for issues with a comment saying " :+1: ".

There is the option to watch an issue -- use this instead. Consider that watching an issue is like voting for it to be done.

This way, if you do not get a satisfactory response, you can reply to this thread with your complains (reopening the issue, and reminding the owner of the repository, in this case, @domnikl) that this pull request should be merged.

__Remember:__, if something as silly as a `composer.phar` file being kept around is really annoying you that much, you can always choose to fork the repository, and delete it!

**Comment by fadoe** [comment]
When every project I clone include the composer.phar, then I have 10 and more composer.phar on my HDD. This are "only" 11MB, but 11 MB I never use!

For me, watching for a issue is not voting for it. It can be against a solution and watch this issue.

**Comment by bocharsky-bw** [comment]
I think @fadoe is right, watching for an issue is not voting for it, you could be interesting accepted it or no only. Also I think if you agree with issue creator, you should write vote sign and it will be enough. If you see other options you could write a comment with vote sign.

**Comment by domnikl** [comment]
Yes, watching it is not voting for it and I do not care as much about the watchers as about the voters.

Regarding this PR: I already said that I would be happy to merge this **if** there is a section in the README on how to install composer (this could be as simple as a link to getcompser.org) and an entry in `.gitignore`. 

@bocharsky-bw this repository is also for developers who do not have that much experience in PHP and therefore might not know composer. I think in the README would be a good place to leave a hint on it to let them know about it.

**Comment by nueckman** [comment]
> Yes, watching it is not voting for it and I do not care as much about the watchers as about the voters.

Even if you don't like votes, you will get one for your feedback:  :+1:  Made my day ;)

**Comment by domnikl** [comment]
@nueckman I think you didn't understand me correctly: votes are not ambiguous as opposed to watches. I therefor like them more and they give me better feedback over what others think about it. :)

**Comment by nueckman** [comment]
@domnikl :flushed: Well, that happens if men want to be capable of multitasking. My bad. But the meta-discussion (vote vs watch) still made my day ;)

**Comment by domnikl** [comment]
@TomasVotruba can you please add a hint in the README file so I can merge this in?

**Comment by TomasVotruba** [comment]
Closing in favor of #140

**Pull request closed without merging**
