### PR TITLE
Fix docker run. Update docker install link. Add Play With Docker

### PR DESCRIPTION
**Pull request by alfredleo**

### CODE REVIEW

**Comment by domnikl** [comment]
Thanks for your PR @alfredleo !
There are two things I would change though.

- What's your intention in doing `chmod +x` in the Makefile and not committing it with the executable rights? git stores them too
- Why did you add Play with Docker? I didn't know it and tried it. It does a good job but DesignPatternsPHP is not about Docker and Docker is already flagged as optional in the README, so I rather keep it simple in this regard.

**Comment by alfredleo** [comment]
1) Will rework that.
2) Agreed, running pwd just for tests has no meaning here.

**Comment by alfredleo** [comment]
Updated.

**Comment by domnikl** [comment]
Thanks for the fast update! PR is good now, merged it

**Pull request merged**
