### PR TITLE
Enhancement: Run phpcs on Travis

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] runs `phpcs` on Travis, as suggested in `README.md`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Travis should not be used to check coding style IMO.

**Comment by bocharsky-bw** [comment]
@GrahamCampbell What could be use for CS check?

**Comment by GrahamCampbell** [comment]
https://styleci.io/

**Comment by localheinz** [comment]
@bocharsky-bw @GrahamCampbell 

Currently, a run of `phpcs` takes about 4 seconds (see https://travis-ci.org/domnikl/DesignPatternsPHP/jobs/70917227#L146), which isn't really too much overhead. We could improve by only running against one PHP version, or alternatively ask someone with admin privileges to set up styleci.io, what do you guys think?

**Comment by GrahamCampbell** [comment]
It's not the time overhead that's the thing I have a problem with. It's the fact I feel travis status should reflect the tests only, not the cs.

**Comment by bocharsky-bw** [comment]
@GrahamCampbell In `Jenkins` you also advise to use `styleci.io`?

**Comment by eddiejaoude** [comment]
I agree with @GrahamCampbell , travis should not be used for **static code analysis**. Look at [Scrutinizer](https://scrutinizer-ci.com/tour/measure-and-improve-code-quality) as an option to do this.

**Comment by domnikl** [comment]
I too would go for Scrutinizer instead of Travis, so I am closing this PR for now.

**Pull request closed without merging**
